[build]
command = "nx run elementar:build:production"
publish = "dist/apps/elementar/browser"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[[redirects]]
from = "/browser/*"
to = "/browser/*"
status = 200
force = false
